services:
  - type: web
    name: tm-sponsorship
    runtime: node
    buildCommand: npm install pnpm -g && pnpm install && pnpm run build
    startCommand: pnpm run start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production