services:
  - type: web
    name: tm-sponsorship-landing-page
    runtime: node
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm run start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    staticPublishPath: ./public